### ISSUE TITLE
[FEATURE] CollectionsFolder 테이블 및 릴레이션 추가, place 테이블 수정

### ISSUE THREAD

**Issue by steadfastree** [DevKor-github/IEUM-back#13]
## Description 
1. place 테이블 수정 사유
- 구글 장소 API를 통해 받아온 카테고리를 모두 저장했었는데, 이를 이음 고유 카테고리로 (Restaurant, Cafe, Bar, Shopping, Stay, Culture) 변환하는 과정에서 어려움이 있어, 대표 카테고리를 담아두는 칼럼을 하나 만드려고 합니다

2. CollectionsFolder
- 회의에서 리마인드된 사항처럼, 저장한 장소 컬렉션은 폴더 단위로 관리가 가능합니다
- 폴더는 인스타그램 장소 컬렉션, 큐레이션 장소 컬렉션을 넣어둘 수 있습니다
- 장소 컬렉션은 여러 개의 폴더에 들어갈 수 있습니다(다대 다 관계 정의)

## Todos
이 기능을 구현하기 위해 필요한 작업을 설명해주세요

- [x] place 테이블에 칼럼 추가
- [x] CollectionsFolder - id, folderName, userId(FK)
- [x] CollectionsFolder와 InstaGuestCollection, UserCurationCollection은 다대 다로 각각 연결

## ETC
이 외에도 고려할 사항이 있다면 작성해주세요.
