### ISSUE TITLE
[FEATURE] 애플 sign in 구현

### ISSUE THREAD

**Issue by heewoong-ahn** [DevKor-github/IEUM-back#15]
## Description 

- 소셜 로그인 중 하나인 애플의 sign in을 구현 

## Todos

- 프론트에서 애플 인증한 유저의 고유 번호 받아오기 
- 받아온 유저 정보 (고유 번호가 될듯) 자체 DB 저장 및 자체 access, refresh token 발급
- 비밀번호는 난수를 해싱하여 임의의 값 저장. 
- initialLogin값이 true라면 나머지 유저 정보를 회원가입 (최초 로그인) 단계에서 필수적으로 기입.

- ~~애플 developer 계정 등록 및 sign in 기능 사용 위한 service 등록~~ 
- ~~passport-apple 모듈 이용한 애플 sign in~~
- ~~받아온 identity token 사용하여 유저 정보 빼내기~~ 
 

- [ ] ~~깃헙 settings에 변수 추가~~ 
- [ ] ~~깃헙 actions에 .env에 추가하기 위한 변수 추가~~
- [ ] ~~배포 후 테스트 해보기~~ 

## ETC

- ~~애플 서비스에 등록하는 redirect URL 이 https의 형태로만 이루어져 해서 local 환경에서 test를 못해봄: 제가 짠 logic대로 흘러가는지와 apple sign in에서 데이터가 잘 받아와 지는지 테스트 해보고 싶은데 애플 sign in에서 https형태의 redirect URL만을 취급해 local 환경에서 test를 못해봤습니다. 이러한 상황일 때, 코드 수정이 필요할 때마다 test를 해보기 위해 계속 pull request를 통한 코드 검증을 해야하는지 잘 모르겠습니다...~~

- ~~http://localhost:3000/apple을 직접 브라우저에 입력하면 apple sign in이 정상적으로 작동하는데, swagger를 통해 작동 시 에러가 발생하여 해결중인데 원인을 잘 모르겠습니다. CORS문제 같기도 합니다. 애플 service에 등록해놓은 origin과 localhost의 origin이 달라서..? 가 추측인데 왜 swagger를 통해 접근 했을 때만 오류가 나는지 잘 모르겠습니다. 
-> apple service에서 등록해놓은 domain으로부터의 request만 처리하도록 되어있는 것 같은 예상이라 test 필요~~

- 애플 sign in 에서는 refreshToken 자체가 accessToken을 발급하는 인증키로 쓰입니다.
AccessToken을 재발급 받을 때, idToken도 같이 재발급 됨 (jwt 형식). idToken decode 통한 인가. (사용자 확인) 
->인증이 필요한 서비스 사용시마다 refreshToken을 통한 애플 api호출 해야함. 

: 성능 측면에서 매번 api를 호출하는 것보다 자체적으로 access, refresh 토큰을 발급해 사용하는 것이 좋을 것 같아서 위에 적힌 todo의 flow를 따르기로 했습니다.

**Comment by steadfastree** [comment]
로컬에서 nginx 설정해서 로컬 호스트 url에 https 발급받을 수 있어요

**Comment by heewoong-ahn** [comment]
아 그렇군요 알려주셔서 감사합니다. 코드 그럼 push하기 전에 시도해보고 올리도록 하겠습니다.

**Comment by heewoong-ahn** [comment]
추가로 settings에서 깃헙 actions secret key를 등록해야하는데 원래 settings가  있던 위치에 settings가 보이지 않습니다..!

**Comment by steadfastree** [comment]
아니면 희웅님 개인 AWS EC2 인스턴스를 파서 거기서 테스트해보세요 백엔드 스터디용으로 만든 인스턴스라거나
프로덕션 서버에서 테스트하는 건 좋은 선택은 아닌 것 같아요

setting은 제가 확인해볼테니 일단 로컬에서 작업해주세요

**Comment by heewoong-ahn** [comment]
백엔드 스터디용으로 만든 인스턴스를 사용하게 되면 우려되는 부분이 무엇인가요?

**Comment by steadfastree** [comment]
아 백엔드 스터디용으로 만든 EC2 인스턴스를 사용해보시라는 말이었어요
프로덕션 서버에서 직접 테스트하는게 아니라!

**Comment by heewoong-ahn** [comment]
아 이해했습니다! 감사합니다.
