### ISSUE TITLE
[FEATURE] 장소 상세 주소 테이블 추가

### ISSUE THREAD

**Issue by steadfastree** [DevKor-github/IEUM-back#7]
## Description 
추후 지역 기반 검색 및 서비스를 위해 장소의 상세 주소를 담은 테이블을 추가하고, placeService에 해당 로직 추가

## Todos
Description과 동일

- [x] 장소 상세 주소 테이블 추가
- [x] 상세 주소 테이블과 Place 테이블 관계 형성 및 전화번호 추가
- [x] 관련 레코드 생성 로직 추가
